# 自动生成的 Push 配置
# 更新时间: 2026-05-08 15:50:00

export PUSH_ENABLED="yes"
export PUSH_CHANNEL="ntfy"
export TELEGRAM_BOT_TOKEN=""
export TELEGRAM_CHAT_ID=""
export GOTIFY_URL="https://sharq.eu.org:2084"
export GOTIFY_TOKEN=""
export GOTIFY_PRIORITY="10"
export NTFY_URL="http://127.0.0.1:8083"
export NTFY_TOPIC="Arena"
export NTFY_USERNAME="admin"
export NTFY_PASSWORD="Plex0819\$"
export NTFY_PRIORITY="4"
export NTFY_TAGS=""
export PUSHPLUS_TOKEN=""
